import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import SmoothScroll from "./components/animation/SmoothScroll";
import { FennecContextProvider } from "./context/FennecContext";
import { WagmiContextProvider } from "./context/WagmiContext";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="overflow-x-hidden">
          <body className={`${quicksand.className} bg-black text-white overflow-x-hidden`}>
      <WagmiContextProvider>
        <FennecContextProvider>
            <div className="fixed z-50 inset-0 pointer-events-none bg-white/[7%]"></div>
            <SmoothScroll />
            <Header />
            {children}
            <Footer />
        </FennecContextProvider>
      </WagmiContextProvider>
          </body>

    </html>
  );
}
